CREATE TABLE IF NOT EXISTS stores (
  ID INT NOT NULL UNIQUE AUTO_INCREMENT,
  gerant_id INT NOT NULL,
  name VARCHAR(20),
  phone VARCHAR(15),
  PRIMARY KEY (ID),
  FOREIGN KEY (gerant_id) REFERENCES users(ID)
)ENGINE=InnoDB;